# Generated by Django 3.1.7 on 2021-05-16 15:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True)),
                ('mobile', models.CharField(default='123456789', max_length=20)),
                ('img', models.ImageField(default='profile1.png', upload_to='pics')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('organization', models.CharField(blank=True, max_length=230, null=True)),
                ('type', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('retailer', 'Retailer'), ('agent', 'Agent')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('APPAREL', 'Apparel'), ('AUTOMOBILES & MOTORCYCLES', 'Automobiles & Motorcycles'), ('BEAUTY & PERSONAL CARE', 'Beauty & Personal Care'), ('CHEMICALS', 'Chemicals'), ('COMPUTER HARDWARE & SOFTWARE', 'Computer Hardware & Software'), ('CONSTRUCTION & REAL ESTATE', 'Construction & Real Estate'), ('CONSUMER ELECTRONICS', 'Consumer Electronics'), ('ELECTRICAL EQUIPMENT SUPPLIES', 'Electrical Equipment Supplies'), ('ENERGY', 'Energy'), ('ENVIRONMENT', 'Environment'), ('FASHION ACCESSORIES', 'Fashion Accessories'), ('FOOD & BEVERAGE', 'Food & Beverage'), ('FURNITURE', 'Furniture'), ('GIFTS & CRAFTS', 'Gifts & Crafts'), ('HARDWARE', 'Hardware'), ('HEALTH & MEDICAL', 'Health & Medical'), ('HOME & GARDEN', 'Home & Garden'), ('HOME APPLIANCES', 'Home Appliances'), ('INDUSTRIAL PARTS & FABRICATION SERVICES', 'Industrial Parts & Fabrication Services'), ('LIGHTS & LIGHTING', 'Lights & Lighting'), ('LUGGAGE, BAGS & CASES', 'Luggage, Bags & Cases'), ('MACHINERY', 'Machinery'), ('MEASUREMENT & ANALYSIS INSTRUMENTS', 'Measurement & Analysis'), ('MINERALS & METALLURGY', 'Minerals & Metallurgy'), ('MULTIPLE PRODUCTS', 'Multiple Products'), ('OFFICE & SCHOOL SUPPLIES', 'Office & School Supplies'), ('PACKING & PRINTING', 'Packing & Printing'), ('RUBBER & PLASTICS', 'rubber & Plastics'), ('SECURITY & PROTECTION', 'Security & Protection'), ('SERVICE EQUIPMENT', 'Service Equipment'), ('SHOES & FOOTWEAR ACCESSORIES', 'Shoes & Footwear Accessories'), ('SPORTS & ENTERTAINMENT', 'Sports & Entertainment'), ('TELECOMMUNICATION', 'Telecommunication'), ('TEXTILE & LEATHER PRODUCT', 'Textile & Leather Product'), ('TIMEPIECES, JEWELRY , EYEWEAR', 'Timepieces, Jewelry , Eyewear'), ('TOOLS', 'Tools'), ('TOYS & HOBBIES', 'Toys & Hobbies'), ('TRANSPORTATION', 'Transportation')], default='APPAREL', max_length=100)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
                ('otherproducts', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_company_registered', models.CharField(blank=True, max_length=255, null=True)),
                ('total_employees', models.CharField(blank=True, choices=[('Fewer than 5', 'Fewer than 5'), ('5 - 10', '5 - 10'), ('11 - 50', '11 - 50'), ('51 - 100', '51 - 100'), ('101 - 200', '101 - 200'), ('201 - 300', '201 - 300'), ('301 - 400', '301 - 400'), ('401 - 500', '401 - 500'), ('over 501', 'over 501')], max_length=255, null=True)),
                ('bussiness_type', models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Trading Company', 'Trading Company'), ('Buying Office', 'Buying Office'), ('Agent', 'Agent'), ('Distributor/Wholesaler', 'Distributor/Wholesaler'), ('Government ministry/Bureau/Commission', 'Government ministry/Bureau/Commission'), ('Association', 'Association'), ('Business Service (Transportation, finance, travel, Ads, etc)', 'Business Service (Transportation, finance, travel, Ads, etc)'), ('Other', 'Other')], max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('company_advantage', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('business_registeration_document', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('location_of_registeration', models.CharField(blank=True, max_length=255, null=True)),
                ('identity_document', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('business_owner', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Verified'), (1, 'Unverified'), (2, 'Hold')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
