# Generated by Django 3.1.7 on 2021-05-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210518_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img1',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img2',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img3',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Profile Image'),
        ),
    ]
