# Generated by Django 3.1.7 on 2021-05-19 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210518_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutus',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img1',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Companys/Product Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img2',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Companys/Product Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img3',
            field=models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Companys/Product Image'),
        ),
    ]
