# Generated by Django 3.1.7 on 2021-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210519_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='123456789', max_length=120),
        ),
    ]
