# Generated by Django 3.1.7 on 2021-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210529_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bussiness_type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('company', 'Trading Company'), ('buying Office', 'Buying Office'), ('agent', 'Agent'), ('distributor/Wholesaler', 'Distributor/Wholesaler'), ('government', 'Government ministry/Bureau/Commission'), ('association', 'Association'), ('business', 'Business Service (Transportation, finance, travel, Ads, etc)'), ('other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('company', 'Trading Company'), ('buying Office', 'Buying Office'), ('agent', 'Agent'), ('distributor/Wholesaler', 'Distributor/Wholesaler'), ('government', 'Government ministry/Bureau/Commission'), ('association', 'Association'), ('business', 'Business Service (Transportation, finance, travel, Ads, etc)'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
