# Generated by Django 3.1.7 on 2021-04-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210429_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='profile1.png', upload_to='blog'),
        ),
    ]
