# Generated by Django 3.1.7 on 2021-05-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
