# Generated by Django 3.1.7 on 2021-05-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210505_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttype',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('retailer', 'Retailer'), ('agent', 'Agent')], max_length=50, null=True),
        ),
    ]
