# Generated by Django 3.1.7 on 2021-05-22 22:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='Dear Sir/Madam,I am looking for products with the following specifications:-'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttype',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('retailer', 'Retailer'), ('agent', 'Agent')], default='buyer', max_length=50, verbose_name='request type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.SlugField(default='Enter Keywords separated by comas. Eg.:cars, bikes', max_length=200),
        ),
    ]
