# Generated by Django 3.1.7 on 2021-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210529_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttype',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('retailer', 'Retailer'), ('agent', 'Agent'), ('service', 'Service')], default='buyer', max_length=50, verbose_name='request type'),
        ),
    ]
