# Generated by Django 3.1.7 on 2021-05-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerseller', '0003_auto_20210515_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='policy_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='show_product',
            field=models.BooleanField(default=False),
        ),
    ]
