# Generated by Django 3.1.7 on 2021-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerseller', '0004_auto_20210517_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='policy_agreed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='policy_agreed',
            field=models.BooleanField(default=True),
        ),
    ]
