# Generated by Django 3.1.7 on 2021-05-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerseller', '0007_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
