# Generated by Django 3.1.7 on 2021-06-07 04:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerseller', '0008_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcomment',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
