# Generated by Django 3.1.7 on 2021-06-09 04:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyerseller', '0009_auto_20210607_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safedeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('buy', models.CharField(choices=[('product', 'Product'), ('services', 'Services'), ('others', 'Others')], default='Product', max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dealvalue', models.PositiveIntegerField()),
                ('commission', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('50%seller50%buyer', '50% Seller, 50% the buyer')], default='Seller', help_text='Goimex Safe service charges a commission for organizing deal protection and guaranteeing the delivery of goods / services. The commission size is up to 3 % for goods, up to 7 % for services. There can be other commissions depending on the conditions and amount of the transaction.', max_length=100)),
                ('logistics', models.CharField(choices=[('own', 'Own'), ('goimex', 'Want to deliver the goods with Goimex Logistics')], default='Seller', help_text='Specify how you want to organize logistics.Goimex Logistics is a service of searching logistics companies, we have trusted freight forwarders working with us. If you want to make delivery through our Logistics, in this case Goimex will also act as a guarantor for delivery.', max_length=100)),
                ('pickup', models.CharField(help_text='From where to pick up the goods?', max_length=500)),
                ('delivery', models.CharField(help_text='Where do you need to deliver the goods? *', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(default='123456789', max_length=120)),
                ('city', models.CharField(max_length=500)),
                ('partnername', models.CharField(help_text='Specify the information of your partner from whom you are buying or to whom you are selling a product or service', max_length=500)),
                ('partnercompany', models.CharField(help_text='The name of the partner company (if it is legal. person)', max_length=500)),
                ('partnerphone', phone_field.models.PhoneField(blank=True, help_text='Partners Contact phone number', max_length=31)),
                ('partneremail', models.EmailField(help_text='Partners Email Address', max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Hold')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safedeal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
