# Generated by Django 3.1.7 on 2021-06-15 17:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyerseller', '0011_auto_20210609_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyerseller.category'),
        ),
        migrations.AlterField(
            model_name='safedeal',
            name='delivery',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='safedeal',
            name='partneremail',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='safedeal',
            name='pickup',
            field=models.CharField(max_length=500),
        ),
    ]
