# Generated by Django 3.1.7 on 2021-06-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerseller', '0012_auto_20210615_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
